  name: lint-check
  on:
    push:
      branches:
        - main
  jobs:
    check:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node: [ 13.x, 14.x, 15.x ]

      steps:
        - name: Install
          run: make install

        - name: ESLint tests
          run: make lint
