  name: lint-check
  on:
    push:
      branches:
        - main
  jobs:
    build:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          node: [13.x, 14.x, 15.x]

      steps:
        - uses: actions/checkout@v2

        - name: Run make Install
          run: make install

        - name: Run make lint
          run: make lint
